# Site settings
title: UMBC Linux Users Group
title-abbrev: umbclug

email: lug@umbc.edu
description: > # this means to ignore newlines until "baseurl:"
  Official site of the UMBC Linux Users Group (umbclug). Find all
  our talks and announcements here.

# url: 'https://lug.umbc.edu'
url: 'https://umbc-linux-users-group.github.io/umbclug.github.io/
# Build settings
markdown: kramdown
permalink: pretty # no .html extension needed/wanted
excerpt_separator: <!--more-->

# Allow events in the future (for calendar feed)
future: true

# These allow RITlug's schedule to be updated site-wide from one
# location. They will appear in pages as they are typed, so it
# is recommended that you follow the format already here when
# updating them.
umbclug-time: 7:00PM - 8:00PM
umbclug-place: SOND 113
umbclug-day: Wednesday

# this allows social links to also be easily updated
social:
  mailinglist: https://groups.google.com/forum/#!forum/ritlug-announce
  discord: https://discord.gg/HqyKN7dZkW
